/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Roboto Flex"', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
        display: ['Fraunces', 'Georgia', 'serif'],
        serif: ['Lora', 'Georgia', 'serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        'm3-xs': 'var(--md-sys-shape-corner-extra-small)',
        'm3-sm': 'var(--md-sys-shape-corner-small)',
        'm3-md': 'var(--md-sys-shape-corner-medium)',
        'm3-lg': 'var(--md-sys-shape-corner-large)',
        'm3-lg-inc': 'var(--md-sys-shape-corner-large-increased)',
        'm3-xl': 'var(--md-sys-shape-corner-extra-large)',
        'm3-xl-inc': 'var(--md-sys-shape-corner-extra-large-increased)',
        'm3-2xl': 'var(--md-sys-shape-corner-extra-extra-large)',
        'm3-full': 'var(--md-sys-shape-corner-full)',
      },
      colors: {
        m3: {
          surface: 'var(--md-sys-color-surface)',
          'surface-dim': 'var(--md-sys-color-surface-dim)',
          'surface-bright': 'var(--md-sys-color-surface-bright)',
          'container-lowest': 'var(--md-sys-color-surface-container-lowest)',
          'container-low': 'var(--md-sys-color-surface-container-low)',
          container: 'var(--md-sys-color-surface-container)',
          'container-high': 'var(--md-sys-color-surface-container-high)',
          'container-highest': 'var(--md-sys-color-surface-container-highest)',
          'on-surface': 'var(--md-sys-color-on-surface)',
          'on-surface-variant': 'var(--md-sys-color-on-surface-variant)',
          primary: 'var(--md-sys-color-primary)',
          'on-primary': 'var(--md-sys-color-on-primary)',
          'primary-container': 'var(--md-sys-color-primary-container)',
          'on-primary-container': 'var(--md-sys-color-on-primary-container)',
          secondary: 'var(--md-sys-color-secondary)',
          'on-secondary': 'var(--md-sys-color-on-secondary)',
          'secondary-container': 'var(--md-sys-color-secondary-container)',
          'on-secondary-container': 'var(--md-sys-color-on-secondary-container)',
          tertiary: 'var(--md-sys-color-tertiary)',
          'on-tertiary': 'var(--md-sys-color-on-tertiary)',
          'tertiary-container': 'var(--md-sys-color-tertiary-container)',
          'on-tertiary-container': 'var(--md-sys-color-on-tertiary-container)',
          outline: 'var(--md-sys-color-outline)',
          'outline-variant': 'var(--md-sys-color-outline-variant)',
        },
      },
    },
  },
  plugins: [],
};
